version: "3.0"
services:
  fast-fourier-transform:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "fast-fourier-transform"
      MODULE_TYPE: "Processing"
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "80"
      EGRESS_URLS: "https://testdockercompose.free.beeceptor.com"
      INPUT_LABEL: "vibrations"
      SAMPLE_SIZE: 1024
    ports:
      - 80:80
